name: Build cEmoji Windows exe

on: 
  push:
    branches:
      - main

jobs:
  build_exe:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install pyinstaller
        pip install shutil
        pip install patool
        pip install -r requirements.txt

    - name: Execute pyinstaller
      run: pyinstaller.exe --noconsole --onefile --strip --icon=my_icon.ico .\cEmoji.py

    - name: Show and zip cEmoji
      run: |
        dir dist
        mkdir cEmoji
        xcopy .\resource\* cEmoji\ /E /I
        copy .\dist\cEmoji.exe cEmoji\
        .\lib\7za.exe a cEmoji.zip cEmoji -r
        .\lib\7za.exe a cEmoji_LZMA.7z cEmoji -r -mx=9 -mm=LZMA
        .\lib\7za.exe l cEmoji.zip
        .\lib\7za.exe l cEmoji_LZMA.7z

    - name: Create Release and Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        tag_name: V0.${{ github.run_id }}
        name: Release V0.${{ github.run_id }}
        # body: TODO New Release.
        body_path: update.md
        draft: true
        prerelease: true
        files: |
          cEmoji.zip
          cEmoji_LZMA.7z
          LICENSE
