name: Build Windows exe

on: 
  push:
    branches:
      - main

jobs:

  build_exe:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install pyinstaller

    - name: Execute pyinstaller
      run: pyinstaller cEmoji.py

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: cEmoji-exe
        path: dist/cEmoji.exe

    - name: Install Scoop
      uses: yokawasa/action-scoop@v1
      with:
          scoop_version: '1.0.252'

    - name: Install GitHub CLI 
      run: scoop install gh

    - name: Create Release and Upload Artifact
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
      run: | 
        gh release create v$(Get-Date -Format yyyyMMddHHmmss)
        gh release upload v$(Get-Date -Format yyyyMMddHHmmss) cEmoji-exe
